### ISSUE TITLE
[adobe-xd] Add Dark mode support

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/mui-design-kits#15]
I didn't see anyone ask for it yet, so it's likely not a high priority.

## Your Environment 🌎

v4.13.0

**Comment by adrianmanea** [comment]
Right now we have the dark variables inside the main document but considering the performance of XD we need to take the same route as Figma--having two separate files. Once we have a stable version of the v5 it shouldn't take us too much.

**Comment by oliviertassinari** [comment]
@adrianmanea To be honest, I'm not sure that many designers are looking for dark mode. If it's easy to bring, then +1.

**Comment by adrianmanea** [comment]
Dark mode has been created!

**Comment by oliviertassinari** [comment]
Closing as included in #32.
