### ISSUE TITLE
[adobe-xd] ButtonGroup has not selected state

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/mui-design-kits#17]
The selected state doesn't exist: https://mui.com/components/button-group/

<img width="540" alt="Screenshot 2021-10-16 at 20 18 45" src="https://user-images.githubusercontent.com/3165635/137598074-7d1ee42c-191b-4ae3-9919-50e347442cb0.png">

## Your Environment 🌎

v4.13.0

**Comment by adrianmanea** [comment]
Selected state has been remove in the v5.

**Comment by oliviertassinari** [comment]
Closing as will come with #32
