### ISSUE TITLE
[figma] Menu component is incomplete vs. production

### ISSUE THREAD

**Issue by brookssolveig** [mui-org/mui-design-kits#2]
The production Menu component offers several features which are absent in the Figma design file.

- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.
- [x] The issue is present in the latest release.

## Current Behavior 😯
The Figma Menu component only supports the default size, it also only has an option to display an icon on the left.

## Expected Behavior 🤔
The Figma menu component should support the dense prop in addition to the default size. It should also include an option to display items on the right, as shown [in the documentation](https://mui.com/components/menus/#icon-menu). Wouldn't hurt to also include a selected state in addition to the resting and default states.

Also, nitpick: the size and padding of the icon included in the Figma file appears to be different than production. Could be wrong here. Prod seems to show a 20x20 icon with 0 padding. Figma displays a 24x24 icon. 

## Steps to Reproduce 🕹
Open the latest Figma file.

## Context 🔦
I want to provide perfect specs to my engineers. I also want to modify components, which requires a perfect understanding of how the component is set up. 

## Your Environment 🌎

5.0.0

**Comment by adrianmanea** [comment]
We just added new variants. This is the ListItem component.
![image](https://user-images.githubusercontent.com/5917515/140486673-93bd44e2-6fd3-47b4-8721-bc81302096d2.png)

**Comment by oliviertassinari** [comment]
This seems fixed in v5.2.0 cc @adrianmanea

**Comment by brookssolveig** [comment]
Thanks y'all! Been slow to respond because I had a kid!
