### ISSUE TITLE
[figma] Default palette colors are out of sync

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/mui-design-kits#25]
Compare the source of truth, https://mui.com/customization/palette/, with the values used in Figma:

![unnamed (1)](https://user-images.githubusercontent.com/3165635/137808627-d7af29f4-5e78-48f7-97d1-b57ac76c0f0e.png)

![unnamed](https://user-images.githubusercontent.com/3165635/137808630-a29336d7-c342-40cc-bc32-b676036286ff.png)

**Comment by oliviertassinari** [comment]
It's fixed in v5.2.0 but there is one thing that I wonder about. Why Day/Night and not light/dark like in https://www.figma.com/community/file/1035203688168086460?

**Comment by adrianmanea** [comment]
That's correct! We used the Day/Night during development to filter the colors more precisely because the shades have the same name. Renamed into Dark/Light to avoid confusing people.
