### ISSUE TITLE
[figma] Consider support for interactive components

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/mui-design-kits#28]
I guess that [interactive components](https://help.figma.com/hc/en-us/articles/360061175334-Create-interactive-components-with-variants) can be particularly interesting for checkboxes/switches. 

## Requests

> sometime soon?

https://mui.zendesk.com/agent/tickets/1460

> Is this something that your team plans to include?

https://mui.zendesk.com/agent/tickets/1528

> a prototype of Material UI components (the difference in state on hover, click) instead of static designs.

https://mui.zendesk.com/agent/tickets/1905

**Comment by Selino** [comment]
> I guess that [interactive components](https://help.figma.com/hc/en-us/articles/360061175334-Create-interactive-components-with-variants) can be interesting for checkboxes/switches.

…and text fields, list items, animated icons (loaders, etc), expanding navigation menu, etc. 😉

**Comment by oliviertassinari** [comment]
At some point, using UXPin or Framer might be more adapted.

**Comment by adrianmanea** [comment]
Totally agree with @oliviertassinari here. The library will get exponentially bigger with just a bunch of duplicated instances with just a background color change. The goal is to produce realistic mockups, not a 1-to-1 browser reproduction. Not to mention the complexity of component overrides it introduces (changing 10 instances vs 40).

IMHO covering the spectrum of the whole state might work if Figma introduces some kind of CSS engine logic like Framer.

We can definitely have *some* interactive components like @oliviertassinari mentioned.

**Comment by adrianmanea** [comment]
Interactive component support for:

Hover and Click for:
- [ ] Checkbox
- [ ] Icon Button
- [ ] Switch
- [ ] Radio Button
- [ ]

**Comment by adrianmanea** [comment]
We have Interactive component support for:

Click interaction for:
- [x] Checkbox
- [x] Switch
- [x] Radio Button
- [x] Accordion
- [ ] Text Field/Select

Hover interaction:
- [x] Button
- [x] Breadcrumbs
- [x] Icon Button
- [x] Link
- [x] Table
- [x] Fab
- [x] Slider
- [x] Chips
- [ ] List
- [ ] Menu
- [ ] Rating
- [ ] Menu

This is the last task we have in our sprint for the new update.

**Comment by oliviertassinari** [comment]
@adrianmanea I had a look, it seems great.

For the button, I believe we miss the [Pressed state](https://material.io/design/interaction/states.html#pressed) and the equivalent interactive Figma binding for "While pressing".

**Comment by adrianmanea** [comment]
The Button component is absolutely maxed out in terms of variants, we even separated its variants as it wouldn't accept more.

If we want to add the "Pressed" state, we need to delete existing variants (e.g the Colors) and only leave one or two.

We did consider covering the pressed state but we do not know what to compromise. We're open to ideas.

**Comment by adrianmanea** [comment]
There is also the problem that if we do have the pressed state for Button we need to do the same thing for all actionable components.

Having available just the "Default", "Inherit", "Primary" and "Secondary" was always on the top of my mind, people have the blueprint on how to do the states for an unavailable color variant (e.g for "Hovered", change the bg. color to the dark shade, change the elevation from 2 to 4 and that's it!). This opens the possibility of adding extra states like "pressed".

Clearly, our decisions were made favoring consistency and trying to cover all levels of experience.

I propose to release as is without the pressed states, and if we get enough feedback towards this being a nice addition we consider our options.

**Comment by oliviertassinari** [comment]
> The Button component is absolutely maxed out in terms of variants

Oh, I didn't know there were a limit. In this case 👍 to close this issue, we did a first iteration. We can wait for designers to complain to guide us in the next step?

**Comment by adrianmanea** [comment]
>We can wait for designers to complain to guide us in the next step?

Yes! This is was I was thinking too.
