### ISSUE TITLE
[adobe-xd] v5.0.0 release

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/mui-design-kits#32]
It's scheduled for the end of the month. People to notify https://material-ui.zendesk.com/agent/tickets/1503.

**Comment by adrianmanea** [comment]
We are almost done. We have a few tasks left like:
- [ ] Solve font style bugs (XD changed the height of the font)
- [ ] Update link component
- [ ] Re-test the responsiveness of the components

-- 1.5 weeks

**Comment by oliviertassinari** [comment]
Done. it's live.
