### ISSUE TITLE
Resize of dialog component

### ISSUE THREAD

**Issue by warikoo** [mui-org/mui-design-kits#33]
Just purchased the fig design components. I added a dialog component to layout a new dialog. When i resize the height of the dialog the actions don't move to the bottom. What am i missing?

**Comment by adrianmanea** [comment]
Hi, all **Dialog** components are built with Auto Layout. The height of the dialog depends on the **DialogContent** size. This is the default behaviour in a browser environment. If you would like the **DialogActions** to stay at the bottom please set the **DialogContent** height on **Fill Container**.

**Comment by warikoo** [comment]
Got it thank you. I see how the behavior can change if needed.
