### ISSUE TITLE
[figma] How to create a multiline TextField?

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/mui-design-kits#34]
## The question from Yaron

Is there an option to create a multiline component didn't figure out how? Those are the props in the Figma file:

<img width="228" alt="Screenshot 2021-11-21 at 12 54 17" src="https://user-images.githubusercontent.com/3165635/142760729-8ab85612-c97c-4ddd-8994-fce7a7b4b325.png">

**Comment by oliviertassinari** [comment]
Here is an example:

https://user-images.githubusercontent.com/3165635/142760706-afc6a535-46a7-458b-9f4b-863d4b2ee343.mp4

**Comment by adrianmanea** [comment]
Actually, in v5 multiline variant is supported by default:

https://user-images.githubusercontent.com/5917515/142822139-9698a482-7ca5-4bc4-a371-7de260218b8b.mov

**Comment by oliviertassinari** [comment]
@adrianmanea Great. I have updated the versions to be exact.
