### ISSUE TITLE
[figma] Merge light and dark modes in one file

### ISSUE THREAD

**Issue by danilo-leal** [mui-org/mui-design-kits#38]
While the MUI Studio team was conducting interviews, a user mentioned that having one Figma file for light mode and another for dark is cumbersome as it demands a duplicated effort to update the other once one has been changed. I'm sure there are benefits to having them separated, especially related to performance given that the file could get considerably larger, but have we considered the option of merging it? I suppose it would be way easier to design with both modes at the same place.

**Comment by adrianmanea** [comment]
This has also crossed my mind, the only concern I had was the performance issues that may arise. Maintaining two separate files is also a struggle as well from our perpsective. I waited for this proposal to come up actually haha.

I'm proposing the following options:

- Merge both themes (referrence [Material 3 Design Kit](https://www.figma.com/community/file/1035203688168086460/Material-3-Design-Kit))
- If performance issues start to appear we can delete variants which can be easily self-created (like a success button)
- Move all unsued icons into a separate file

Problems may arise:

- Lag issues when working in the same file
- Updating from the v5
- Other?

Should we wait for others input before moving forward with this?

**Comment by oliviertassinari** [comment]
> Should we wait for others input before moving forward with this?

👍

**Comment by danilo-leal** [comment]
For making it official I guess so, yes! But maybe we could already give it a spin to test it out and see whether Figma gets too laggy or not, just in case?!

**Comment by adrianmanea** [comment]
> For making it official I guess so, yes! But maybe we could already give it a spin to test it out and see whether Figma gets too laggy or not, just in case?!

Yes! We'll test this out with a few components. I'll get back at this thread when done.

**Comment by adrianmanea** [comment]
Good news! It works fine so far considering we also have all material icons style in the same file. If you want to check out the progress here's a preview: https://www.figma.com/file/n7JwXE0hDtjetTmTZ8oaRL/(Alpha)MUI-for-Figma-v5.0.2?node-id=6583%3A45995

Quick question, the light/dark versions should also separate the Typography as well? In my short research, people are theming only the colors. Considering the fact that the app lets you have different typography/shadows/colors in a new theme what would be the best approach? Keep in mind that customization time is doubled if we separate the typography.

**Comment by danilo-leal** [comment]
Why would separating the typography make the customization time double?

I was looking at it and I think we could instead use variants to have only one component but with both modes. So, instead of having two major components, one for light and another for dark, where the user would have to open the menu, go back and select the right mode, we could merge them all into one and add a mode toggle.

| Current approach      | Variant approach |
| ----------- | ----------- |
| <img width="400" alt="Screen Shot 2021-12-13 at 21 42 44" src="https://user-images.githubusercontent.com/67129314/145912347-dc1c1fdc-2065-406c-801a-e5615bb35f54.png"> | <img width="400" alt="Screen Shot 2021-12-13 at 21 47 04" src="https://user-images.githubusercontent.com/67129314/145912353-8b0e23ee-07f0-4ab9-bd5b-7de0042edd83.png">  |

Let me know what do you think! Overall, I believe it's easier for quick toggling. It's an opportunity to in the future have an MUI official plugin to toggle a whole frame quickly between modes, there are already some doing this out there.

**Comment by adrianmanea** [comment]
The decision behind separating components into themes is that people would usually design an app either in light or dark mode. Having the dark mode toggle definitely looks cleaner! I'm +1 for doing this way, my only concern is that it might get frustrating when designing only in dark mode, having to toggle for each instance? I'm just shooting ideas.

Pros:
- Fewer components in the left search panel
- Fewer components in general
- Cleaner look for components

Cons:
- Designing a dark-mode-first app might be frustrating
- Biased towards light mode

**Comment by adrianmanea** [comment]
So, we bumped into this issue:
![image](https://user-images.githubusercontent.com/5917515/145986298-92b1a1d9-245d-4b25-b7c4-dbfb3aa115b5.png)

Options:
- Separate into components (Button Contained, Button Outlined & Button Text) but this is clearly a breaking change for v5.0.0 users
- Remove all color variants altogether leaving only the Primary and Default since default requires knowing what colors is using (M3 Google Library is doing the same, only one color is available but I found it rather difficult to reproduce the states using another color)
- Separate dark mode components 😵‍💫

I would lean towards option #1 or #3 but I don't want to make this decision alone. What's your decision?

**Comment by danilo-leal** [comment]
Yeah, it's nice to bring up the trade-off and it's also hard to point what would be the definite best choice. But I am too leaning towards having the toggle. I've seen a few marketing sites with only dark mode but as far as apps go, most of them have both. Take [Linear](https://linear.app/) as an example. Their marketing stuff is all black, but the app itself has multiple themes. So yeah, let's do it and gather feedback!

**Comment by danilo-leal** [comment]
PS: I knew that this existed - https://www.figma.com/community/plugin/731176732337510831/Themer :)

**Comment by oliviertassinari** [comment]
> Their marketing stuff is all black, but the app itself has multiple themes. 

I have seen the same trend in the dev tool space, this seems to be trendy nowadays.

**Comment by oliviertassinari** [comment]
More examples:

- [https://planetscale.com/](https://planetscale.com/)
- [https://www.merge.dev/](https://www.merge.dev/)
- [https://airbyte.io/](https://airbyte.io/)

Actually, this might tip us on possible design trend for Joy 😁

**Comment by oliviertassinari** [comment]
Done in v5.2.0
