### ISSUE TITLE
"level" misspelled as "leve" on List page (in blue Alert panel)

### ISSUE THREAD

**Issue by theoskye** [mui-org/mui-design-kits#46]
![Screen Shot 2022-01-06 at 4 15 17 PM](https://user-images.githubusercontent.com/103045/148606075-f3372b23-0e24-47a6-8d23-d81f9348f278.png)

**Comment by oliviertassinari** [comment]
Thanks for the feedback. @adrianmanea already fixed it for the upcoming v5.2.0 release: https://www.figma.com/file/xbYrstJhixECNOhnE5xstK/(Alpha)MUI-for-Figma-v5.2.0?node-id=7292%3A45174.
