### ISSUE TITLE
[figma] Add responsive support?

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/mui-design-kits#5]
https://mui.zendesk.com/agent/tickets/1247

> It would be wonderful for you to add separate type scales and components for different breakpoints/screen sizes eg. Mobile, Tablet, and not just desktop. 

> The breakpoints you use in your design system are good to see, however, I was referring to having a dedicated mobile, tablet, and desktop type scale and components/assets designed to be used at these breakpoints/screen sizes. In your Figma file, the type scale is just for desktop and most of the components are designed at a single size, not at multiple breakpoint sizes. 

https://mui.zendesk.com/agent/tickets/1408

> I am working on a mobile-first project and not on an app project. I was wondering if the components are only designed for app purposes or are they responsive to create desktop versions of my screen? 

## Your Environment 🌎

v5.0.0

**Comment by adrianmanea** [comment]
I think this is done as well, we've added a layout component and screens for each breakpoint!

Ref: https://www.figma.com/file/n7JwXE0hDtjetTmTZ8oaRL/MUI-for-Figma-Material-Components-v5.2.0?node-id=4662%3A14

**Comment by oliviertassinari** [comment]
The link seems outdated, but back to this issue. What I understand is we have the following cases to cover:

- AppBar, different paddingX on xs.
- Tabs, no scroll buttons on xs and sm
- MenuItem, larger height on xs & dense={false}
- Slider, smaller paddingY when the primary modality is a touch screen

If you feel it's done, we can close.

**Comment by adrianmanea** [comment]
That's interesting, we did not cover all components now that you mentioned. Are these all components modifying properties on XS?

- [x] AppBar
- [x] Tabs
- [x] MenuItem
- [ ] Slider

> Slider, smaller paddingY when the primary modality is a touch screen

Is there any way we can simulate this on a desktop environment so we can see the changes?

**Comment by oliviertassinari** [comment]
> Is there any way we can simulate this on a desktop environment so we can see the changes?

This behavior can be reproduced by using the Chrome mobile simulator. However, it only imzpcts the outter padding. It's meant to allow enough touch surface for finders to use the slider. I'm not sure how this should be handled in the Figma component.

The source:

https://github.com/mui-org/material-ui/blob/8efc59254540b66ec445d71d00ff75d5a78581c6/packages/mui-material/src/Slider/Slider.js#L87

**Comment by adrianmanea** [comment]
Got it! I don't think it's worth duplicating all variants for the Slider just to change the padding IMHO. If there are no objections we can close this issue.
